# docker-compose.override.yml - Development overrides
# ===================================================

version: '3.8'

services:
  backend:
    volumes:
      - ./backend:/app:delegated
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=True
    command: python run.py --host=0.0.0.0 --port=5000 --debug

  frontend:
    volumes:
      - ./frontend:/usr/share/nginx/html:delegated