# docker-compose.prod.yml - Production configuration
# =================================================

version: '3.8'

services:
  db:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro

  backend:
    build:
      target: production
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - GUNICORN_WORKERS=4
      - GUNICORN_THREADS=2
    command: gunicorn --bind 0.0.0.0:5000 --workers 4 --threads 2 --timeout 60 --keep-alive 2 --max-requests 1000 --preload run:app

  celery_worker:
    build:
      target: production
    command: celery -A app.celery worker --loglevel=info --concurrency=2

  celery_beat:
    build:
      target: production

  frontend:
    volumes:
      - ./config/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro